-- Создаём нашу базу
CREATE DATABASE RESTAURANT CHARACTER SET = 'utf8';
-- Выбираем нашу базу
USE RESTAURANT;
-- Создаём пользователя со всеми правами для нашей базы,
-- могущего заходить откуда угодно
-- username: root
-- password: (без пароля!!!!)
GRANT ALL PRIVILEGES
ON RESTAURANT.*
TO food@localhost
IDENTIFIED BY 'food'
WITH GRANT OPTION;
GRANT ALL PRIVILEGES
ON RESTAURANT.*
TO food@"%"
IDENTIFIED BY 'food'
WITH GRANT OPTION;
-- Дальше создаём таблицы
USE RESTAURANT;
CREATE TABLE CATEGORIES (
	CAT_ID			INT		UNSIGNED AUTO_INCREMENT	PRIMARY KEY,
	CAT_NAME		VARCHAR(50)
);
CREATE TABLE DISHES (
	DISH_ID				INT		UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_CAT_ID		INT,
	DISH_NAME			VARCHAR(50),
	DISH_PRICE			INT,
	DISH_PHOTO			VARCHAR(50),
	DISH_DESCR			VARCHAR(255),
	DISH_AVAIL			CHAR,
	DISH_PREP_TIME		TIME,
	DISH_WEIGHT			VARCHAR(50)
);
CREATE TABLE ORDERINFO (
	OINFO_ID		INT		UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USER_USER_ID	INT,
	OINFO_DATE		DATETIME,
	OINFO_STATUS	CHAR
);
CREATE TABLE ORDERSPEC (
	OSPEC_ID		INT		UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ORDERINFO_OINFO_ID	INT,
	DISH_DISH_ID	INT,
	OSPEC_QUANTITY	INT
);
CREATE TABLE USERS (
	USER_ID			INT		UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USER_PASSWORD	VARCHAR(50),
	USER_ROLE		VARCHAR(50),	
	USER_NAME		VARCHAR(50),
	USER_EMAIL		VARCHAR(50),
	USER_PHONE		VARCHAR(50)	
);
CREATE TABLE ATTACHMENTS (
	ATT_ID			INT		UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USER_USER_ID		INT,
	ATT_NAME		VARCHAR(50),
	ATT_PATH		VARCHAR(255),
	ATT_MODIFIED	DATETIME		
);


