USE RESTAURANT ;
-- задаём блюда
INSERT INTO `DISHES`   VALUES (1,1,'Салат из трех видов мяса',20,'C:\\Java_EE\\photodb\\1_Salads\\01_Mushroom_salad.jpg','Салат из трех видов мяса','1','00:30:00',175);
INSERT INTO `DISHES`   VALUES (2,1,'Салат из утиной грудки',25,'C:\\Java_EE\\photodb\\1_Salads\\02_Greek_salad.jpg','Салат из утиной грудки','1','00:30:00',170);
INSERT INTO `DISHES`   VALUES (3,1,'Салат Микс с креветками',28,'C:\\Java_EE\\files\\photodb\\1_Salads\\03_Cesaк_salad.jpg','Салат Микс с креветками','1','01:00:00',300);
INSERT INTO `DISHES`   VALUES (4,1,'Салат Мясной',34,'C:\\Java_EE\\photodb\\1_Salads\\04_Summer_salad.jpg','Салат Мясной','1','00:45:00',200);
INSERT INTO `DISHES`   VALUES (5,1,'Салат Оливье',42,'C:\\Java_EE\\photodb\\1_Salads\\05_Mosaic_salad.jpg','Салат Оливье','2','00:14:00',260);
INSERT INTO `DISHES`   VALUES (6,1,'Салат с креветками и апельсином',18,'C:\\Java_EE\\photodb\\1_Salads\\06_Fruit_salad.jpg','Салат с креветками и апельсином','1','00:30:00',170);
INSERT INTO `DISHES`   VALUES (7,1,'Салат с ростбифом и пикантным сыром',13,'C:\\Java_EE\\photodb\\1_Salads\\07_Meat_salad.jpg','Салат с ростбифом и пикантным сыром','1','00:10:00',100);
INSERT INTO `DISHES`   VALUES (8,1,'Салат Тайский',25,'C:\\Java_EE\\photodb\\1_Salads\\08_Calamary_salad.jpg','Салат Тайский','4','00:45:00',300);
INSERT INTO `DISHES`   VALUES (9,1,'Салат Цезарь с куриным филе',27,'C:\\Java_EE\\photodb\\1_Salads\\09_Georgian_salad.jpg','Салат Цезарь с куриным филе','2','00:45:00',250);
INSERT INTO `DISHES`   VALUES (10,1,'Салат Цезарь с креветками',38,'C:\\Java_EE\\photodb\\1_Salads\\10_Simple_salad.jpg','Салат Цезарь с креветками','3','00:15:00',60);
INSERT INTO `DISHES`   VALUES (11,2,'Суши острые с креветкой',54,'C:\\images\\011.jpg','Суши острые с креветкой',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (12,2,'Суши острые с лососем',67,'C:\\images\\012.jpg','Суши острые с лососем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (13,2,'Суши с икрой летучей рыбы (Тобико Суши)',52,'C:\\images\\013.jpg','Суши с икрой летучей рыбы (Тобико Суши)',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (14,2,'Суши с лососем',58,'C:\\images\\014.jpg','Суши с лососем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (15,2,'Суши с угрем (Унаги Суши)',42,'C:\\images\\015.jpg','Суши с угрем (Унаги Суши)',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (16,3,'Ролл Лосось и авокадо',36,'C:\\images\\016.jpg','Ролл Лосось и авокадо',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (17,3,'Ролл с лососем',53,'C:\\images\\017.jpg','Ролл с лососем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (18,3,'Ролл с угрем',64,'C:\\images\\018.jpg','Ролл с угрем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (19,3,'Ролл Филадельфия',51,'C:\\images\\019.jpg','Ролл Филадельфия',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (20,3,'Ролл Калифорния',46,'C:\\images\\020.jpg','Ролл Калифорния',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (21,4,'Креветки в сливочном соусе',74,'C:\\images\\021.jpg','Креветки в сливочном соусе',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (22,4,'Креветки тигровые в беконе',78,'C:\\images\\022.jpg','Креветки тигровые в беконе',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (23,4,'Мидии в раковине под зеленым маслом',65,'C:\\images\\023.jpg','Мидии в раковине под зеленым маслом',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (24,4,'Темпура из кальмара',62,'C:\\images\\024.jpg','Темпура из кальмара',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (25,4,'Темпура из креветок',59,'C:\\images\\025.jpg','Темпура из креветок',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (26,4,'Шашлычки из креветок в соусе Терияки',68,'C:\\images\\026.jpg','Шашлычки из креветок в соусе Терияки',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (27,5,'Говядина в сливочном соусе с запеченным картофелем',90,'C:\\images\\027.jpg','Говядина в сливочном соусе с запеченным картофелем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (28,5,'Говяжья вырезка на открытом огне (шашлык)',95,'C:\\images\\028.jpg','Говяжья вырезка на открытом огне (шашлык)',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (29,5,'Жаркое мясное в сливочном соусе',118,'C:\\images\\029.jpg','Жаркое мясное в сливочном соусе',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (30,5,'Каре барашка в пармезановой корочке',105,'C:\\images\\030.jpg','Каре барашка в пармезановой корочке',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (31,5,'Медальоны из свинины с грибами',95,'C:\\images\\031.jpg','Медальоны из свинины с грибами',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (32,5,'Отбивная из свинины в льезоне',97,'C:\\images\\032.jpg','Отбивная из свинины в льезоне',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (33,5,'Печень говяжья с беконом (Мангал)',85,'C:\\images\\033.jpg','Печень говяжья с беконом (Мангал)',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (34,5,'Плов Узбекский из говядины, закладка на 1 казан',75,'C:\\images\\034.jpg','Плов Узбекский из говядины, закладка на 1 казан',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (35,5,'Свинина по - домашнему',78,'C:\\images\\035.jpg','Свинина по - домашнему',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (36,5,'Свиные ребрышки тушеные в пиве',65,'C:\\images\\036.jpg','Свиные ребрышки тушеные в пиве',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (37,5,'Стейк из свиной корейки в пармезановой корочке',58,'C:\\images\\037.jpg','Стейк из свиной корейки в пармезановой корочке',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (38,5,'Стейк Пять перцев из говяжьей вырезки',69,'C:\\images\\038.jpg','Стейк Пять перцев из говяжьей вырезки',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (39,5,'Стейк Рибай с запеченным картофелем',74,'C:\\images\\039.jpg','Стейк Рибай с запеченным картофелем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (40,10,'Десерт Карамельный Семифредо',26,'C:\\images\\040.jpg','Десерт Карамельный Семифредо',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (41,10,'Десерт Панна Кота',28,'C:\\images\\041.jpg','Десерт Панна Кота',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (42,10,'Десерт Тирамису',31,'C:\\images\\042.jpg','Десерт Тирамису',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (43,10,'Жареное мороженое',15,'C:\\images\\043.jpg','Жареное мороженое',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (44,10,'Штрудель яблочный',24,'C:\\images\\044.jpg','Штрудель яблочный',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (45,10,'Шоколадный кекс Брауниз',33,'C:\\images\\045.jpg','Шоколадный кекс Брауниз',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (46,10,'Фруктовая темпура',31,'C:\\images\\046.jpg','Фруктовая темпура',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (47,6,'Грибной крем - суп',29,'C:\\images\\047.jpg','Грибной крем - суп',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (48,6,'Солянка мясная',24,'C:\\images\\048.jpg','Солянка мясная',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (49,6,'Лапша Удон с мясом',38,'C:\\images\\049.jpg','Лапша Удон с мясом',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (50,6,'Суп - лапша куриная',45,'C:\\images\\050.jpg','Суп - лапша куриная',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (51,6,'Суп Pasta e Fagioli',52,'C:\\images\\051.jpg','Суп Pasta e Fagioli',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (52,6,'Суп Минестроне ',41,'C:\\images\\052.jpg','Суп Минестроне ',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (53,6,'Уха с лососем',42,'C:\\images\\053.jpg','Уха с лососем',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (54,6,'Окрошка сборная мясная',48,'C:\\images\\054.jpg','Окрошка сборная мясная',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (55,7,'Байкал',10,'C:\\images\\055.jpg','Байкал',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (56,7,'Кисель',12,'C:\\images\\056.jpg','Кисель',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (57,7,'Крем-сода',15,'C:\\images\\057.jpg','Крем-сода',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (58,7,'Лимонад',13,'C:\\images\\058.jpg','Лимонад',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (59,7,'Морс',18,'C:\\images\\059.jpg','Морс',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (60,7,'Пепси',14,'C:\\images\\060.jpg','Пепси',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (61,7,'Кофе',26,'C:\\images\\061.jpg','Кофе',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (62,7,'Чай',20,'C:\\images\\062.jpg','Чай',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (63,7,'Фанта',15,'C:\\images\\063.jpg','Фанта',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (64,7,'Белый чай',11,'C:\\images\\064.jpg','Белый чай',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (65,7,'Желтый чай',12,'C:\\images\\065.jpg','Желтый чай',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (66,8,'Лонг-Айленд',37,'C:\\images\\066.jpg','равные части водки, джина, текилы и рома; апельсиновый ликер, кола, лёд',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (67,8,'Маргарита',44,'C:\\images\\067.jpg','текила, трипл-сек, сок цитрусовых',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (68,8,'Беллини',35,'C:\\images\\068.jpg','игристое вино и свежее персиковое пюре',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (69,8,'Мимоза',42,'C:\\images\\069.jpg','шампанское и апельсиновый сок',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (70,8,'Россини',46,'C:\\images\\070.jpg','игристое вино и свежее клубничное пюре',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (71,8,'Тинторетто',29,'C:\\images\\071.jpg','игристое вино и натуральный гранатовый сок',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (72,8,'Куба либре',33,'C:\\images\\072.jpg','светлый ром, кока-кола',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (73,8,'Мохито',35,'C:\\images\\073.jpg','ром, мята, лайм, сельтерская, сахар',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (74,9,'Закуска из запеченных баклажан',54,'C:\\images\\074.jpg','Закуска из запеченных баклажан с кедровыми орешками',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (75,9,'Домашний попкорн с пряностями',56,'C:\\images\\075.jpg','Домашний попкорн с пряностями',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (76,9,'Бутерброды',58,'C:\\images\\076.jpg','Бутерброды с помидорами, авокадо и тар-таром',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (77,9,'Тартар из лосося или семги',46,'C:\\images\\077.jpg','Тартар из лосося или семги',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (78,9,'Маринованная семга в масле',48,'C:\\images\\078.jpg','Маринованная семга в масле',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (79,9,'Маринованные баклажаны',65,'C:\\images\\079.jpg','Маринованные баклажаны с чесноком и мятой',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (80,9,'Блины',63,'C:\\images\\080.jpg','Блины с красной рыбой и сливочным кремом',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (81,2,'Эдома Нигири',48,'C:\\images\\081.jpg','креветки, слабосолёный лосось, копчёный угорь',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (82,2,'Нигири Торо ',56,'C:\\images\\082.jpg','суши с сердцевидкой + васаби',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (83,2,'Какинохадзуси ',54,'C:\\images\\083.jpg','Лист хурмы',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (84,2,'Тякиндзуси, обернутые омлетом',26,'C:\\images\\084.jpg','Омлет, семга',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (85,2,'Икура гункан макидзуси',47,'C:\\images\\085.jpg','Суши (Морковь и абрикос)',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (86,3,'Туго наки',39,'C:\\images\\086.jpg','рис, нори, креветка, лосось копченый,',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (87,3,'Флорида',42,'C:\\images\\087.jpg','рис, нори, лосось, авакадо, огурец, майонез, тобико, кунжут',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (88,3,'Токио',55,'C:\\images\\088.jpg','рис, нори, угорь, ананас, сыр \"Филадельфия\"',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (89,3,'Сиам',49,'C:\\images\\089.jpg','рис, нори, лосось, угорь, икра, сыр \"Филадельфия\" ',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (90,3,'Сейко',51,'C:\\images\\090.jpg','рис, нори, угорь, огурец, тобико, сыр \"Филадельфия\"',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (91,4,'Рыба, жаренная в кляре',68,'C:\\images\\091.jpg','филе рыбы, соль, перец, специи, растительное масло ',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (92,4,'Заливная рыба',74,'C:\\images\\092.jpg','Рыба, лук, морковь, желатин, лавровый лист',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (93,4,'Щука фаршированная',54,'C:\\images\\093.jpg',' Щука, рис, зелень',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (94,4,'Рыба с картофелем, запеченные под майонезом',32,'C:\\images\\094.jpg','Рыба, картофель, помидоры',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (95,6,'Украинский борщ',22,'C:\\images\\095.jpg','Украинский борщ',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (96,6,'Постный борщ',18,'C:\\images\\096.jpg','Постный борщ',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (97,8,'Кофе с ромом и вишневым ликером',17,'C:\\images\\097.jpg','Кофе с ромом и вишневым ликером',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (98,8,'Молочный шейк с черникой',15,'C:\\images\\098.jpg','Молочный шейк с черникой',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (99,9,'Салат \"Курица с сухариками\"',19,'C:\\images\\099.jpg','Салат \"Курица с сухариками\"',NULL,NULL,NULL);
INSERT INTO `DISHES`   VALUES (100,9,'Рулет из лаваша',23,'C:\\images\\100.jpg','Рулет из лаваша',NULL,NULL,NULL);

-- Задаём категории
INSERT INTO `categories`   VALUES (1,'Салаты','images/DISHES/cat01/Category page_salads.jpg');
INSERT INTO `categories`   VALUES (2,'Суши','/images/DISHES/cat02/Category page_sushi.jpg');
INSERT INTO `categories`   VALUES (3,'Роллы','/images/DISHES/cat03/Category page_rolls.jpg');
INSERT INTO `categories`   VALUES (4,'Рыбные блюда','/images/DISHES/cat04/Category page_fishdish.jpg');
INSERT INTO `categories`   VALUES (5,'Горячие закуски','/images/DISHES/cat05/Category page_Hot appetizers.jpg');
INSERT INTO `categories`   VALUES (6,'Первые блюда','/images/DISHES/cat06/Category page_First course.jpg');
INSERT INTO `categories`   VALUES (7,'Напитки безалкогольные','/images/DISHES/cat07/Category page_Non alcohol drinks.jpg');
INSERT INTO `categories`   VALUES (8,'Коктейли','/images/DISHES/cat08/Category page_Coctails.jpg');
INSERT INTO `categories`   VALUES (9,'Холодные закуски','/images/DISHES/cat09/Category page_Cold.jpg');
INSERT INTO `categories`   VALUES (10,'Десерты','/images/DISHES/cat10/Category page_Deserts.jpg');

-- Задаём пользователей
INSERT INTO `users` VALUES (1,  'admin', '21232f297a57a5a743894a0e4a801fc3', 'admin@aaa.com', 1, '111-111', 'ROLE_ADMIN');
INSERT INTO `users` VALUES (2,  'root',  '63a9f0ea7bb98050796b649e85481845', 'root@bbb.bbb.com', 1, '222-222', 'ROLE_ADMIN');
INSERT INTO `users` VALUES (3,  'user1', '24c9e15e52afc47c225b757e7bee1f9d', 'user1.user1@c.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (4,  'user2', '7e58d63b60197ceb55a1c487989a3720', 'u2@aaa.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (5,  'user3', '92877af70a45fd6a2ed7fe81e1236b78', 'eee@aaa.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (6,  'user4', '3f02ebe3d7929b091e3d8ccfde2f3bc6', 'fff@aaa.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (7,  'user5', '0a791842f52a0acfbb3a783378c066b8', 'aaa@c.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (8,  'user6', 'affec3b64cf90492377a8114c86fc093', 'aaa@bbb.bbb.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (9,  'user7', '3e0469fb134991f8f75a2760e409c6ed', 'aaa@aaa.com', 1, '322-223', 'ROLE_USER');
INSERT INTO `users` VALUES (10, 'user8', '7668f673d5669995175ef91b5d171945', 'aaa@aaa.com', 1, '322-223', 'ROLE_USER');

-- Задаём заказы
INSERT INTO `orderinfo` VALUES (1, 1, '2012-1-1 00:00:01', 'A');
INSERT INTO `orderinfo` VALUES (2, 1, '2012-11-10 12:20:01', 'A');
INSERT INTO `orderinfo` VALUES (3, 3, '2012-10-1 23:00:01', 'B');
INSERT INTO `orderinfo` VALUES (4, 1, '2012-5-15 05:05:01', 'B');
INSERT INTO `orderinfo` VALUES (5, 10, '2012-6-6 06:40:30', 'A');
INSERT INTO `orderinfo` VALUES (6, 1, '2012-9-10 11:11:11', 'A');
INSERT INTO `orderinfo` VALUES (7, 3, '2012-5-1 05:50:55', 'C');
INSERT INTO `orderinfo` VALUES (8, 2, '2012-1-1 00:00:01', 'A');
INSERT INTO `orderinfo` VALUES (9, 1, '2012-1-1 00:00:01', 'A');
INSERT INTO `orderinfo` VALUES (10, 5, '2012-1-1 00:00:01', 'C');
INSERT INTO `orderinfo` VALUES (17, 1, '2012-11-2 00:00:00', 'A');
INSERT INTO `orderinfo` VALUES (18, 1, '2012-11-2 00:00:00', 'A');
INSERT INTO `orderinfo` VALUES (19, 1, '2012-11-2 00:00:00', 'A');
INSERT INTO `orderinfo` VALUES (20, 1, '2012-11-2 00:00:00', 'A');
INSERT INTO `orderinfo` VALUES (22, 1, '2012-11-2 00:00:00', 'A');

-- Задаём спецификации заказов					
INSERT INTO `orderspec` VALUES (1, 1, 1, 1);
INSERT INTO `orderspec` VALUES (2, 1, 2, 1);
INSERT INTO `orderspec` VALUES (3, 1, 10, 10);
INSERT INTO `orderspec` VALUES (4, 4, 4, 4);
INSERT INTO `orderspec` VALUES (5, 1, 5, 1);
INSERT INTO `orderspec` VALUES (6, 2, 7, 1);
INSERT INTO `orderspec` VALUES (7, 3, 6, 1);
INSERT INTO `orderspec` VALUES (8, 5, 4, 4);
INSERT INTO `orderspec` VALUES (9, 6, 2, 100);
INSERT INTO `orderspec` VALUES (10, 10, 1, 10);
INSERT INTO `orderspec` VALUES (11, 20, 4, 1);
INSERT INTO `orderspec` VALUES (13, 22, 6, 1);

-- Задаём аттачменты
INSERT INTO `attachments` VALUE (1, 1, 1, '', '',  '');		
INSERT INTO `attachments` VALUE (2, 1, 1, '', '',  '');		
INSERT INTO `attachments` VALUE (3, 2, 1, '', '',  '');		
INSERT INTO `attachments` VALUE (4, 3, 2, '', '',  '');		
INSERT INTO `attachments` VALUE (5, 3, 3, '', '',  '');		
INSERT INTO `attachments` VALUE (6, 6, 4, '', '',  '');		
INSERT INTO `attachments` VALUE (7, 6, 1, '', '',  '');		
INSERT INTO `attachments` VALUE (8, 8, 4, '', '',  '');		
INSERT INTO `attachments` VALUE (9, 8, 6, '',  '', '');		
INSERT INTO `attachments` VALUE (10, 10, 5, '', '','');		
